homeassistant: !include homeassistant.yaml

logger:
  default: info
  logs:
    homeassistant.helpers.template: error

default_config:

# custom config
group: !include_dir_named groups/
scripts: !include_dir_named scripts/
automation: !include_dir_list automation/
scene: !include_dir_list scenes/
proximity: !include_dir_merge_named proximity/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/

input_boolean: !include_dir_named input_boolean/
input_select: !include_dir_named input_select/
input_datetime: !include_dir_named input_datetime/
input_text: !include_dir_named input_text/
timer: !include_dir_named timers/

light: !include_dir_merge_list light/
switch: !include_dir_merge_list switch/

alarm_control_panel: !include_dir_list alarm/
